name: Deploy LittleLink to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Prepare publish directory
        run: |
          set -e
          mkdir _publish
          # Copy everything from root except what we don't want to deploy
          rsync -av \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'README.md' \
            --exclude 'LICENSE' \
            ./ _publish/

          # Optional: ensure Pages niceties
          touch _publish/.nojekyll
          # echo "links.yourdomain.tld" > _publish/CNAME  # if you want to ship a CNAME file

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _publish
          name: github-pages
          retention-days: 1

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4